"""initial_schema

Revision ID: d1aed3c42f77
Revises: 
Create Date: 2026-06-21 22:52:46.836570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1aed3c42f77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('repo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('repo_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('commit',
    sa.Column('sha', sa.Text(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('committed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('files', sa.Integer(), nullable=True),
    sa.Column('insertions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('sha')
    )
    op.create_table('contributor',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('prs', sa.Integer(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('issues', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('username', 'repo_id')
    )
    op.create_table('issue',
    sa.Column('issue_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('resolution_hrs', sa.Float(), nullable=True),
    sa.Column('labels', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('milestone', sa.Text(), nullable=True),
    sa.Column('comments', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('issue_id', 'repo_id')
    )
    op.create_table('pull_request',
    sa.Column('pr_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('merged_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cycle_hours', sa.Float(), nullable=True),
    sa.Column('review_hours', sa.Float(), nullable=True),
    sa.Column('changed_files', sa.Integer(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('pr_id', 'repo_id')
    )
    op.create_table('workflow_run',
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.repo_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_run')
    op.drop_table('pull_request')
    op.drop_table('issue')
    op.drop_table('contributor')
    op.drop_table('commit')
    op.drop_table('repository')
    # ### end Alembic commands ###
